Add docker image and go modules
tomtom-international/alertmanager-webhook-logger pull request #3
Opened 2021-05-13 19:02 UTC by julienduchesne

go mod simplifies the build and the Dockerfile is useful since it's very likely that this would be used in Kubernetes

2021-05-17 06:35 UTC, kbudde commented on Dockerfile
> +FROM alpine:3.13
I know alpine image is quite small but I suspect it is not needed:
```
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -installsuffix 'static' . 

FROM scratch
```

2021-05-17 06:38 UTC, kbudde requested changes
I think dropping root priviliges is a must have.

Personally I would prefer a static build with image "scratch" as final.

2021-05-17 06:38 UTC, kbudde commented on Dockerfile
> +
You should not use root.
```
RUN mkdir /etc && \
    echo 'nobody:x:65534:65534:nobody:/:' > /etc/passwd && \
    echo 'nobody:x:65534:' > /etc/group

# Perform any further action as an unprivileged user.
USER nobody:nobody
```

2021-05-25 04:54 UTC, yvesmueller-tomtom commented
This PR looks quite good. Could you please use an unprivileged user in the docker container as suggest by @kbudde ? I am fine with the Alpine image.

2021-07-07 10:30 UTC, julienduchesne commented
Thanks for the reviews @yvesmueller-tomtom and @kbudde, and sorry for the delay. I switched the image to use scratch and an unprivileged user!

2021-07-07 10:41 UTC, kbudde approved these changes
LGTM

2021-07-08 05:39 UTC, merged